genome:
  hg19:
    - index_path: "/home/niek/Documents/references/bowtie2-index/hg19/bowtie2-hg19"
    - black_list_path: "/home/niek/Documents/references/blacklists/Human/hg19/wgEncodeDukeMapabilityRegionsExcludable.bed"
  hg38:
    - index_path: "/home/niek/Documents/references/bowtie2-index/GRCh38.p13.genome-index/GRCh38.p13.genome-index"
    - black_list_path: "/home/niek/Documents/references/blacklists/Human/hg38/hg38-blacklist.v2.bed"
  mm9:
    - index_path: "/home/niek/Documents/references/bowtie2-index/mouse/mm9/mm9.genome-index"
    - black_list_path: "/home/niek/Documents/references/blacklists/Mouse/mm9-blacklist.bed"
