bigWig:
  binSize: "10"
  normalizeUsing: "RPKM"
  extendReads: "200"
  effectiveGenomeSize: "2827437033"
peaks:
  TF:
    - peak: "narrowPeak"
    - fragments: 120 #if an integer is provided, fragements below this number (bp) are kept, otherwise enter "all" to keep all reads
    - use-duplicates: "TRUE"
  histone: 
    - peak: "broadPeak"
    - fragments: "all"
    - use-duplicates: "TRUE"
