bigWig:
  binSize: "10"
  normalizeUsing: "RPKM"
  extendReads: "200"
  effectiveGenomeSize: "2827437033"
ngsplot:
  feature: "tss"
  window: 3000
MACS2:
  format: "AUTO"
  genome: "hs"
  genome-size: 2.7e9
  qvalue: 0.05
  extsize: 200
peaks:
  TF:
    - peak: "narrowPeak"
    - fragments: 120 #if an integer is provided, fragements below this number (bp) are kept, otherwise enter "all" to keep all reads
    - use-duplicates: "TRUE"
  histone: 
    - peak: "broadPeak"
    - fragments: "all"
    - use-duplicates: "TRUE"
